{
 "title": "ClusterDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result((simplyblock_cluster_read_operations_total{cluster=~\".*\"}  and on() (absent(_{_=\"admin\"}) and absent(_{_=\"${__user.login}\"}))) or on() (simplyblock_cluster_read_operations_total{cluster=\"${__user.login}\"}  unless on() (absent(_{_!=\"admin\"}) and absent(_{_=\"${user.login}\"}))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cluster_size_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_size_total_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_size_free_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_size_used_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_prov",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_size_provisioned_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_prov_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * simplyblock_cluster_size_provisioned_bytes{cluster=\"$Cluster\"} / simplyblock_cluster_size_total_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_size_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * simplyblock_cluster_size_used_bytes{cluster=\"$Cluster\"} / simplyblock_cluster_size_total_bytes{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "cluster_write_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_write_bytes_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_write_bytes_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_write_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_write_latency_ticks_total{cluster=\"$Cluster\"}[$__rate_interval]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_write_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "simplyblock_cluster_write_operations_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_write_operations_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_wite_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 23 },
   "targets": [
    {
     "expr": "simplyblock_cluster_write_latency_ticks_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "cluster_read_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_read_bytes_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_read_bytes_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_read_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_read_latency_ticks_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_read_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "simplyblock_cluster_read_operations_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 39 },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_read_operations_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_read_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 39 },
   "targets": [
    {
     "expr": "simplyblock_cluster_read_latency_ticks_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "unmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "cluster_unmap_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "simplyblock_cluster_unmap_latency_ticks_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_bytes_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_unmap_bytes_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_unmap_latency_ticks_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_io_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(simplyblock_cluster_unmap_operations_total{cluster=\"$Cluster\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 54 },
   "targets": [
    {
     "expr": "simplyblock_cluster_unmap_operations_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_unmap_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_cluster_unmap_bytes_total{cluster=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}