{
 "title": "DevicesDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "query_result((simplyblock_cluster_read_operations_total{cluster=~\".*\"}  and on() (absent(_{_=\"admin\"}) and absent(_{_=\"${__user.login}\"}))) or on() (simplyblock_cluster_read_operations_total{cluster=\"${__user.login}\"}  unless on() (absent(_{_!=\"admin\"}) and absent(_{_=\"${user.login}\"}))))"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "query_result(simplyblock_device_size_total_bytes{cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "query_result(simplyblock_device_size_total_bytes{cluster=~\"$cluster\",snode=~\"$node\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "device_size_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_device_size_total_bytes{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_size_free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_device_size_free_bytes{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_size_used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_device_size_used_bytes{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_size_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * simplyblock_device_size_used_bytes{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"} / simplyblock_device_size_total_bytes{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "device_write_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_device_write_bytes_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(simplyblock_device_write_bytes_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_write_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_device_write_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_write_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "simplyblock_device_write_operations_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "rate(simplyblock_device_write_operations_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_wite_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 24 },
   "targets": [
    {
     "expr": "simplyblock_device_write_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "device_read_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_device_read_bytes_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(simplyblock_device_read_bytes_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_read_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_device_read_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_read_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "simplyblock_device_read_operations_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "rate(simplyblock_device_read_operations_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_read_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 41 },
   "targets": [
    {
     "expr": "simplyblock_device_read_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "unmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "device_unmap_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "simplyblock_device_unmap_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_unmap_bytes_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(simplyblock_device_unmap_bytes_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_unmap_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_device_unmap_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_unmap_io_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(simplyblock_device_unmap_operations_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_unmap_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "simplyblock_device_unmap_operations_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "device_unmap_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "simplyblock_device_unmap_bytes_total{cluster=~\"$cluster\",snode=~\"$node\",device=~\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}