{
 "title": "NodesDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "query_result((simplyblock_cluster_read_operations_total{cluster=~\".*\"}  and on() (absent(_{_=\"admin\"}) and absent(_{_=\"${__user.login}\"}))) or on() (simplyblock_cluster_read_operations_total{cluster=\"${__user.login}\"}  unless on() (absent(_{_!=\"admin\"}) and absent(_{_=\"${user.login}\"}))))"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "query_result(simplyblock_device_size_total_bytes{cluster=~\"$cluster\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "snode_size_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_size_total_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_size_free_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_size_used_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_prov",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_size_provisioned_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_prov_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * simplyblock_snode_size_provisioned_bytes{cluster=~\"$cluster\",snode=~\"$node\"} / simplyblock_snode_size_total_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_size_util",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * simplyblock_snode_size_used_bytes{cluster=~\"$cluster\",snode=~\"$node\"} / simplyblock_snode_size_total_bytes{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "snode_write_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_write_bytes_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_write_bytes_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_wite_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "simplyblock_snode_write_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_write_io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "simplyblock_snode_write_operations_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "write_iops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_write_operations_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_write_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_write_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "snode_read_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_read_bytes_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_read_bytes_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_read_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_read_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_read_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "simplyblock_snode_read_operations_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read_iops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 40 },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_read_operations_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_read_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "simplyblock_snode_read_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "unmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "snode_unmap_latency_ticks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "simplyblock_snode_unmap_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_bytes_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_unmap_bytes_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_latency_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_unmap_latency_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_io_ps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(simplyblock_snode_unmap_operations_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_io",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 55 },
   "targets": [
    {
     "expr": "simplyblock_snode_unmap_operations_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_unmap_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "simplyblock_snode_unmap_bytes_total{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "health_check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "snode_health_check",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "simplyblock_snode_health_check{cluster=~\"$cluster\",snode=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "snode_cpu_busy_percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "100 * rate(simplyblock_snode_thread_busy_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) / on(cluster,cluster_name,snode,hostname,core_id) group_left(thread_name) (rate(simplyblock_snode_reactor_busy_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) + rate(simplyblock_snode_reactor_idle_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snode_cpu_core_utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 64 },
   "targets": [
    {
     "expr": "100 * (rate(simplyblock_snode_reactor_busy_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) + rate(simplyblock_snode_reactor_irq_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) + rate(simplyblock_snode_reactor_sys_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])) / ((rate(simplyblock_snode_reactor_busy_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) + rate(simplyblock_snode_reactor_irq_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]) + rate(simplyblock_snode_reactor_sys_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval])) + rate(simplyblock_snode_reactor_idle_ticks_total{cluster=~\"$cluster\",snode=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}