[tox]
envlist = unit, integration, lint, types
skipsdist = true
requires = tox-uv>=1

[testenv]
basepython = python3.9
deps =
    -r requirements.txt
    -r test-requirements.txt

[testenv:lint]
deps = ruff
commands = ruff check

[testenv:types]
deps =
    -r requirements.txt
    -r type-requirements.txt
    mypy
commands = mypy simplyblock_web simplyblock_cli simplyblock_core

[testenv:unit]
commands = pytest tests/unit/ simplyblock_core/test/ {posargs}

[testenv:integration]
commands = pytest tests/integration/ \
    --ignore=tests/integration/ftt2 \
    --ignore=tests/integration/expansion_sim \
    --ignore=tests/integration/migration \
    {posargs}
