# syntax=docker/dockerfile:1
FROM redhat/ubi10:10.1

LABEL name="simplyblock"
LABEL vendor="Simplyblock"
LABEL version="1.0.0"
LABEL release="1"
LABEL summary="Simplyblock controlplane plane component"
LABEL description="Simplyblock controlplane plane container"
LABEL maintainer="developers@simplyblock.io"


RUN dnf config-manager addrepo --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

RUN dnf install -y wget dmidecode pciutils sudo nano gdisk openssh-clients util-linux pkg-config hostname\
    ca-certificates curl kmod docker-ce-cli python3.13 python3-pip iputils iproute iscsi-initiator-utils
#Error: Unable to find a match: nvme-cli  parted

ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
        echo "ARM64 version"; \
    	wget https://github.com/apple/foundationdb/releases/download/7.3.69/foundationdb-clients-7.3.69-1.el9.aarch64.rpm; \
        rpm -ivh --nodigest --nofiledigest foundationdb-clients-7* ; \
    else \
        echo "AMD64 version"; \
        wget https://github.com/apple/foundationdb/releases/download/7.3.69/foundationdb-clients-7.3.69-1.el7.x86_64.rpm; \
        rpm -ivh --nodigest --nofiledigest foundationdb-clients-7* ; \
    fi

COPY LICENSE /licenses/LICENSE

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip setuptools
RUN pip3 install -r requirements.txt

RUN dnf clean all

RUN useradd -ms /bin/bash simplyblock
RUN echo "simplyblock  ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER simplyblock

