{{- if .Values.ingress.useHostPort }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplyblock-api-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: simplyblock-webappapi
                port:
                  number: 5000
---
{{- else if (not .Values.ingress.useHostPort) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplyblock-api-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    nginx.ingress.kubernetes.io/{{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: simplyblock-webappapi
                port:
                  number: 5000
{{- end }}
