apiVersion: v1
kind: Service
metadata:
  name: simplyblock-webappapi
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: simplyblock-webappapi
  ports:
  - name: http
    port: 5000
    targetPort: 5000

