apiVersion: v1
kind: Service
metadata:
  name: simplyblock-webappapi
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: simplyblock-webappapi
  ports:
  - name: http
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    foundationdb.org/fdb-cluster-name: simplyblock-fdb-cluster
  name: simplyblock-fdb-cluster-external
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    foundationdb.org/fdb-process-class: storage
  ports:
  - port: 4501
    targetPort: 4501
    protocol: TCP
