{{- if .Values.tls.serviceCA.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: simplyblock-spdkproxy
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: simplyblock-spdkproxy-tls
spec:
  clusterIP: None
  ports: []
{{- end }}
