apiVersion: v1
kind: Service
metadata:
  name: simplyblock-webappapi
  namespace: {{ .Release.Namespace }}
  {{- if .Values.tls.serviceCA.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: simplyblock-webappapi-tls
  {{- end }}
spec:
  selector:
    app: simplyblock-webappapi
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplyblock-webappapi
  namespace: {{ .Release.Namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
    reloader.stakater.com/configmap: "simplyblock-fdb-cluster-config"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplyblock-webappapi
  template:
    metadata:
      annotations:
        log-collector/enabled: "true"
      labels:
        app: simplyblock-webappapi
    spec:
      serviceAccountName: simplyblock-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: simplyblock-webappapi
              topologyKey: kubernetes.io/hostname

      {{- if .Values.nodeSelector.create }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.create }}
      tolerations:
      {{- range .Values.tolerations.list }}
      - operator: {{ .operator | quote }}
        {{- if .effect }}
        effect: {{ .effect | quote }}
        {{- end }}
        {{- if .key }}
        key: {{ .key | quote }}
        {{- end }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- end }}
      {{- end }}
      {{- end }}           
      containers:
      - name: webappapi
        image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
        imagePullPolicy: "{{ .Values.image.simplyblock.pullPolicy }}"
        ports:
        - containerPort: 5000
        command: ["python", "simplyblock_web/app.py"]
        env:
        - name: SIMPLYBLOCK_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: simplyblock-config
              key: LOG_LEVEL
        - name: LVOL_NVMF_PORT_START
          value: "{{ .Values.ports.lvolNvmfPortStart }}"
        - name: ENABLE_MONITORING
          value: "{{ .Values.observability.enabled }}"
        - name: PROMETHEUS_URL
          value: "{{ .Values.prometheus.simplyblock.prometheusURL }}"
        - name: PROMETHEUS_PORT
          value: "{{ .Values.prometheus.simplyblock.prometheusPORT }}"
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.observability.enabled }}
        - name: MONITORING_SECRET
          valueFrom:
            secretKeyRef:
              name: simplyblock-grafana-secrets
              key: MONITORING_SECRET
{{- end }}
        - name: FLASK_DEBUG
          value: "False"
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: fdb-cluster-file
          mountPath: /etc/foundationdb/fdb.cluster
          subPath: fdb.cluster
        {{- if .Values.tls.serviceCA.enabled }}
        - name: tls
          mountPath: /etc/simplyblock/tls
          readOnly: true
        - name: service-ca
          mountPath: /etc/ssl/certs/service-ca.crt
          subPath: service-ca.crt
          readOnly: true
        {{- end }}
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
      - name: fluent-bit
        image: fluent/fluent-bit:1.8.11
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: config
            mountPath: /fluent-bit/etc/
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
      volumes:
      - name: fdb-cluster-file
        configMap:
          name: simplyblock-fdb-cluster-config
          items:
            - key: cluster-file
              path: fdb.cluster
      - name: varlog
        hostPath:
          path: /var/log
      - name: config
        configMap:
          name: simplyblock-fluent-bit-config
      {{- if .Values.tls.serviceCA.enabled }}
      - name: tls
        secret:
         secretName: simplyblock-webappapi-tls
      - name: ca
        configMap:
          name: simplyblock-ca
      {{- end }}
