observability:
  enabled: true
  secret: "sWbpOgba1bKnCfcPkVQi"
  deletionInterval: "3d"
  level: "DEBUG"
  graylog:
    rootPasswordSha2: "b87c15a8ae4736d771ca60a7cc2014baaeab19b11c31f5fedef9421958a403c9"
    passwordSecret: "is6SP2EdWg0NdmVGv6CEp5hRHNL7BKVMFem4t9pouMqDQnHwXMSomas1qcbKSt5yISr8eBHv4Y7Dbswhyz84Ut0TW6kqsiPs"
    maxNumberIndex: "3"
    retentionPeriod: "7d"
  grafana:
    endpoint: ""
    contactPoint: "https://hooks.slack.com/services/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"

image:
  simplyblock: 
    repository: "simplyblock/simplyblock"
    tag: "main-snapshot-replication"
    pullPolicy: "Always"
  manager:
    repository: "simplyblock/simplyblock-manager"
    tag: "snapshot_replication"
    pullPolicy: "Always"

tolerations:
  create: false
  list:
  - operator: Exists
    effect:
    key: 
    value:
nodeSelector:
  create: false
  key: 
  value:

ports:
  lvolNvmfPortStart: 9100

csiHostpathDriver:
  enabled: false

storageclass:
  name:  
  allowedTopologyZones: []


foundationdb:
  multiAZ: false

mongodb:
  name: "simplyblock-mongodb"
  deployment_name: "simplyblock-mongodb"
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 250m
      memory: 1Gi
  community:
    mongodb:
      repo: quay.io/mongodb
      imageType: ubi8
    agent:
      name: mongodb-agent
      version: 108.0.2.8729-1
    registry:
      agent: quay.io/mongodb

  registry:
    operator: quay.io/mongodb
    agent: quay.io/mongodb
    readinessProbe: quay.io/mongodb
    versionUpgradeHook: quay.io/mongodb

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - mongodb
          topologyKey: "kubernetes.io/hostname"

opensearch:
  fullnameOverride: "simplyblock-opensearch"
  singleNode: true
  replicas: 1

  antiAffinity: "hard"
  persistence:
    enabled: true
    image: busybox
    storageClass:
    size: 20Gi
  image:
    repository: "opensearchproject/opensearch"
    tag: ""
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "3Gi"

  extraEnvs:
    # - name: OPENSEARCH_JAVA_OPTS
    #   value: "-Xms1g -Xmx1g"
    - name: bootstrap.memory_lock
      value: "true"
    - name: action.auto_create_index
      value: "false"
    - name: plugins.security.ssl.http.enabled
      value: "false"
    - name: plugins.security.disabled
      value: "true"

  securityConfig:
    enabled: false

prometheus:
  simplyblock:
    prometheusURL: simplyblock-prometheus
    prometheusPORT: 9090    
  server:
    fullnameOverride: simplyblock-prometheus
    enabled: true
    statefulSet:
      enabled: true
    name: simplyblock-prometheus
    replicaCount: 1
    image:
      repository: quay.io/prometheus/prometheus
      tag: ""    
    podLabels:
      app: simplyblock-prometheus
    podAnnotations:
      log-collector/enabled: "true"
      reloader.stakater.com/auto: "true"
      reloader.stakater.com/configmap: "sbcli-simplyblock-prometheus-config"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - simplyblock-prometheus
            topologyKey: "kubernetes.io/hostname"
    service:
      servicePort: 9090
      type: ClusterIP
      gRPC:
        enabled: true
        servicePort: 10901
      additionalPorts:
        - name: http-thanos
          port: 10902
          targetPort: 10902
          protocol: TCP
    securityContext:
      fsGroup: 65534
    persistentVolume:
      enabled: true
      size: 5Gi
      storageClass:
    extraArgs:
      storage.tsdb.min-block-duration: 2h
      storage.tsdb.max-block-duration: 2h
    sidecarContainers:
      thanos-sidecar:
        image: thanosio/thanos:v0.31.0
        args:
          - sidecar
          - --tsdb.path=/prometheus
          - --prometheus.url=http://localhost:9090
          - --objstore.config-file=/etc/thanos/objstore.yml
        ports:
          - name: grpc
            containerPort: 10901
          - name: http
            containerPort: 10902
        volumeMounts:
          - name: storage-volume
            mountPath: /prometheus
          - name: objstore-config
            mountPath: /etc/thanos
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "1Gi"
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    configMapOverrideName: simplyblock-prometheus-config
    extraVolumes:
      - name: objstore-config
        configMap:
          name: simplyblock-objstore-config
  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  kube-state-metrics:
    enabled: false
  configmapReload:
    prometheus:
      repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.72.0


reloader:
  nameOverride: simplyblock-reloader
  fullnameOverride: simplyblock-reloader
  reloader:
    deployment:
      image:
        name: ghcr.io/stakater/reloader
        tag: v1.3.0

ingress:
  enabled: false
  ingressClassName: nginx
  useDNS: false
  host: ""
  tlsSecret: 
  controller:
    hostNetwork: true  
    dnsPolicy: ClusterFirstWithHostNet
    replicaCount: 2
    image:
      registry: "quay.io/simplyblock-io"
      image: ingress-nginx-controller
      tag: "v1.10.1"
    service:
      type: ClusterIP
    extraArgs:
      tcp-services-configmap: "simplyblock/simplyblock-tcp-services"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress
            topologyKey: "kubernetes.io/hostname"
    nodeSelector: {}


simplyblock:
  cluster:
    clusterName: simplyblock-cluster
    mgmtIfname: eth0
    fabric: tcp
    isSingleNode: false
    enableNodeAffinity: false
    strictNodeAntiAffinity: false
    warningThreshold:
      capacity: 80
      provisionedCapacity: 80
    criticalThreshold:
      capacity: 90
      provisionedCapacity: 90

  pool:
    name: simplyblock-pool
    capacityLimit: 100Gi

  lvol:
    name: simplyblock-lvol
    
  storageNodes:
    name: simplyblock-node
    clusterImage: simplyblock/simplyblock:main-snapshot-replication
    mgmtIfname: eth0
    maxLogicalVolumeCount: 10
    maxSize: 0
    partitions: 0
    corePercentage: 65
    spdkDebug: false
    spdkImage:
    coreIsolation: false
    skipKubeletConfiguration: false
    enableCpuTopology: false
    workerNodes:

  devices:
    name: simplyblock-devices

  tasks:
    name: simplyblock-task
