graylog:
  rootPasswordSha2: "b87c15a8ae4736d771ca60a7cc2014baaeab19b11c31f5fedef9421958a403c9"
  passwordSecret: "is6SP2EdWg0NdmVGv6CEp5hRHNL7BKVMFem4t9pouMqDQnHwXMSomas1qcbKSt5yISr8eBHv4Y7Dbswhyz84Ut0TW6kqsiPs"

monitoring:
  enabled: true
  secret: "sWbpOgba1bKnCfcPkVQi"

log:
  deletionInterval: "3d"
  retentionPeriod: "7d"
  level: "DEBUG"
  maxNumberIndex: "3"

grafana:
  endpoint: ""
  contactPoint: "https://hooks.slack.com/services/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"

image:
  simplyblock:
    repository: "quay.io/simplyblock-io/simplyblock"
    tag: "R25.10-Hotfix-quay"
    pullPolicy: "Always"

tolerations:
  create: false
  list:
  - operator: Exists
    effect:
    key:
    value:
nodeSelector:
  create: false
  key:
  value:

ports:
  lvolNvmfPortStart:

storageclass:
  allowedTopologyZones: []

foundationdb:
  multiAZ: false

mongodb:
  name: "simplyblock-mongodb"
  deployment_name: "simplyblock-mongodb"
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 250m
      memory: 1Gi
  community:
    mongodb:
      repo: quay.io/simplyblock-io
      name: mongodb-community-server
      imageType: ubi8
    agent:
      name: mongodb-agent
      version: 108.0.2.8729-1
    registry:
      agent: quay.io/simplyblock-io
  registry:
    operator: quay.io/simplyblock-io
    agent: quay.io/simplyblock-io
    readinessProbe: quay.io/simplyblock-io
    versionUpgradeHook: quay.io/simplyblock-io
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - mongodb
          topologyKey: "kubernetes.io/hostname"

opensearch:
  fullnameOverride: "simplyblock-opensearch"
  singleNode: true
  replicas: 1

  antiAffinity: "hard"
  persistence:
    enabled: true
    image: quay.io/simplyblock-io/busybox
    storageClass: local-hostpath
    size: 10Gi
  image:
    repository: "quay.io/simplyblock-io/opensearch"
    tag: ""

  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "3Gi"

  extraEnvs:
    - name: bootstrap.memory_lock
      value: "true"
    - name: action.auto_create_index
      value: "false"
    - name: plugins.security.ssl.http.enabled
      value: "false"
    - name: plugins.security.disabled
      value: "true"

  securityConfig:
    enabled: false

prometheus:
  simplyblock:
    prometheusURL: simplyblock-prometheus
    prometheusPORT: 9090
  server:
    fullnameOverride: simplyblock-prometheus
    enabled: true
    statefulSet:
      enabled: true
    name: simplyblock-prometheus
    replicaCount: 1
    image:
      repository: quay.io/simplyblock-io/prometheus
      tag: ""
    podLabels:
      app: simplyblock-prometheus
    podAnnotations:
      log-collector/enabled: "true"
      reloader.stakater.com/auto: "true"
      reloader.stakater.com/configmap: "sbcli-simplyblock-prometheus-config"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - simplyblock-prometheus
            topologyKey: "kubernetes.io/hostname"
    service:
      servicePort: 9090
      type: ClusterIP
      gRPC:
        enabled: true
        servicePort: 10901
      additionalPorts:
        - name: http-thanos
          port: 10902
          targetPort: 10902
          protocol: TCP
    securityContext:
      fsGroup: 65534
    persistentVolume:
      enabled: true
      size: 5Gi
      storageClass: local-hostpath
    extraArgs:
      storage.tsdb.min-block-duration: 2h
      storage.tsdb.max-block-duration: 2h
    sidecarContainers:
      thanos-sidecar:
        image: quay.io/simplyblock-io/thanos:v0.31.0
        args:
          - sidecar
          - --tsdb.path=/prometheus
          - --prometheus.url=http://localhost:9090
          - --objstore.config-file=/etc/thanos/objstore.yml
        ports:
          - name: grpc
            containerPort: 10901
          - name: http
            containerPort: 10902
        volumeMounts:
          - name: storage-volume
            mountPath: /prometheus
          - name: objstore-config
            mountPath: /etc/thanos
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "1Gi"
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    configMapOverrideName: simplyblock-prometheus-config
    extraVolumes:
      - name: objstore-config
        configMap:
          name: simplyblock-objstore-config
  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  prometheus-node-exporter:
    enabled: false

  kube-state-metrics:
    enabled: false
  configmapReload:
    prometheus:
      image:
        repository: quay.io/simplyblock-io/prometheus-config-reloader
        tag: v0.72.0


reloader:
    nameOverride: simplyblock-reloader
    fullnameOverride: simplyblock-reloader
    reloader:
      deployment:
        image:
          name: quay.io/simplyblock-io/reloader
          tag: v1.3.0
ingress:
  enabled: true
  ingressClassName: nginx
  useDNS: false
  host: ""
  tlsSecret:
  controller:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    replicaCount: 2
    image:
      registry: "quay.io/simplyblock-io"
      image: ingress-nginx-controller
      tag: "v1.10.1"
    service:
      type: ClusterIP
    extraArgs:
      tcp-services-configmap: "simplyblock/simplyblock-tcp-services"
    opentelemetry:
      enabled: false
      name: opentelemetry
      image:
        registry: "quay.io/simplyblock-io"
        image: opentelemetry
        tag: "v20230721-3e2062ee5"
    admissionWebhooks:
      enabled: true
      patch:
        image:
          registry: "quay.io/simplyblock-io"
          image: kube-webhook-certgen
          tag: "v1.4.1"
          digest: ""
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress
            topologyKey: "kubernetes.io/hostname"
    nodeSelector: {}
  defaultBackend:
    enabled: false
    name: defaultbackend
    image:
      registry: "quay.io/simplyblock-io"
      image: defaultbackend-amd64
      tag: "1.5"

