name: Docker Helm Deployer Build

on:
  workflow_dispatch:
    inputs:
      sbcli_branch:
        description: "sbcli branch to clone (leave empty to skip)"
        required: false
        default: "main"
        type: choice
        options:
          - main
      csi_branch:
        description: "simplyblock-csi branch to clone (leave empty to skip)"
        required: false
        default: "master"
        type: choice
        options:
          - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hamdysimplyblock
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        run: |
          docker buildx create --name mybuilder --bootstrap --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg SBCLI_BRANCH="${{ github.event.inputs.sbcli_branch }}" \
            --build-arg CSI_BRANCH="${{ github.event.inputs.csi_branch }}" \
            -t simplyblock/helm-deployer:latest \
            -f docker/Dockerfile.helm-deployer \
            . --push

          echo "::notice title=Docker.com::simplyblock/helm-deployer:latest"
